module.exports = {
    user: {
        notFound: "User not found!",
        createSuccess: "User created successfully!",
        updateSuccess: "User updated successfully!",
        deleteSuccess: "User deleted successfully!",
        fetchSuccess: "User fetched successfully!",
        fetchAllSuccess: "All users fetched successfully!",
        idRequired: "User id required!",
        updateFailed: "User update failed!",
        deleteFailed: "User delete failed!",
        fetchFailed: "User fetch failed!",
        createFailed: "User create failed!",
        tokenRequired: "Token required!",
        invalidToken: "Invalid token!",
        passwordRequired: "Password required!",
        invalidPassword: "Invalid password!",
        emailRequired: "Email required!",
        invalidEmail: "Invalid email!",
        usernameRequired: "Username required!",
        invalidUsername: "Invalid username!",
        nameRequired: "Name required!",
        statusRequired: "Status required!",
        userblocked: "User blocked!",
        loginSuccess: "User logged in successfully!",
        loginFailed: "User login failed!",
        invalidCredentials: "Invalid credentials!",
        notAuthorized: "User not authorized!",
        
    },
    product: {
        notFound: "Product not found!",
        createSuccess: "Product created successfully!",
        updateSuccess: "Product updated successfully!",
        deleteSuccess: "Product deleted successfully!",
        fetchSuccess: "Product fetched successfully!",
        fetchAllSuccess: "All products fetched successfully!",
        idRequired: "Product id required!",
        updateFailed: "Product update failed!",
        deleteFailed: "Product delete failed!",
    }
}